# Generated by Django 5.2.6 on 2025-09-05 15:25

import attendance.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='Nombre completo')),
                ('id_number', models.CharField(max_length=32, unique=True, verbose_name='ID Number')),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Fecha')),
                ('check_in', models.DateTimeField(blank=True, null=True, verbose_name='Hora ingreso')),
                ('check_out', models.DateTimeField(blank=True, null=True, verbose_name='Hora salida')),
                ('evidence_photo', models.ImageField(blank=True, null=True, upload_to=attendance.models.evidence_upload_path, verbose_name='Foto constancia')),
                ('notes', models.CharField(blank=True, max_length=200, verbose_name='Observaciones')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='attendance.employee', verbose_name='Empleado')),
            ],
            options={
                'ordering': ['-date', 'employee__full_name'],
                'unique_together': {('employee', 'date')},
            },
        ),
    ]
