# Generated by Django 5.2.6 on 2025-09-05 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_employee_hourly_rate_employee_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='employees',
            field=models.ManyToManyField(blank=True, related_name='projects', to='attendance.employee'),
        ),
    ]
