# Generated by Django 5.2.6 on 2025-09-06 16:11

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_project_employees'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Inicio')),
                ('end_date', models.DateField(verbose_name='Fin')),
                ('status', models.CharField(choices=[('OPEN', 'Abierta'), ('CLOSED', 'Cerrada')], default='OPEN', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='attendance.project', verbose_name='Proyecto (opcional)')),
            ],
            options={
                'ordering': ['-start_date'],
                'unique_together': {('start_date', 'end_date', 'project')},
            },
        ),
        migrations.CreateModel(
            name='PayrollLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minutes', models.PositiveIntegerField(default=0)),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('base_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('adjustment', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Ajuste (+/-)')),
                ('notes', models.CharField(blank=True, max_length=200, verbose_name='Notas ajuste')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='attendance.employee')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='attendance.payrollperiod')),
            ],
            options={
                'ordering': ['employee__full_name'],
                'unique_together': {('period', 'employee')},
            },
        ),
    ]
