# Generated by Django 5.2.6 on 2025-09-08 23:37

import secrets
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_payrollperiod_closed_at_payrollperiod_closed_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='qr_secret',
            field=models.CharField(default=secrets.token_urlsafe, editable=False, max_length=64),
        ),
    ]
