# Generated by Django 5.2.6 on 2025-09-30 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_project_qr_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='manual_minutes',
            field=models.PositiveIntegerField(blank=True, help_text='Override de minutos netos (ya con reglas aplicadas).', null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='manual_note',
            field=models.CharField(blank=True, max_length=200, verbose_name='Motivo ajuste'),
        ),
    ]
