# Generated by Django 5.2.6 on 2025-11-17 04:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_attendance_manual_minutes_attendance_manual_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_uuid', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('action', models.CharField(choices=[('in', 'in'), ('out', 'out')], max_length=10)),
                ('device_ts', models.DateTimeField()),
                ('server_ts', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(default='qr', max_length=20)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='attendance.employee')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='attendance.project')),
            ],
            options={
                'ordering': ['-server_ts'],
                'indexes': [models.Index(fields=['employee', 'server_ts'], name='attendance__employe_0d34ec_idx')],
            },
        ),
    ]
